include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
    use_key_in_widget_constructors: false
